// Generated by Wrangler on Thu Sep 12 2024 12:33:09 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
    // If you set another name in wrangler.toml as the value for 'binding',
    // replace "AI" with the variable name you defined.
	AI: Ai;
}
